// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using macAccess.DB;

#nullable disable

namespace macAccess.Migrations
{
    [DbContext(typeof(MacAccessContext))]
    [Migration("20211221162846_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("macAccess.Classes.MacMini", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MacMinis");
                });

            modelBuilder.Entity("macAccess.Classes.MacMiniData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CPU")
                        .HasColumnType("int");

                    b.Property<int>("HDD")
                        .HasColumnType("int");

                    b.Property<int?>("MacMiniId")
                        .HasColumnType("int");

                    b.Property<int>("Netzwerk")
                        .HasColumnType("int");

                    b.Property<int>("RAM")
                        .HasColumnType("int");

                    b.Property<int>("SSD")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MacMiniId");

                    b.ToTable("MacMiniDatas");
                });

            modelBuilder.Entity("macAccess.Classes.MacMiniData", b =>
                {
                    b.HasOne("macAccess.Classes.MacMini", "MacMini")
                        .WithMany()
                        .HasForeignKey("MacMiniId");

                    b.Navigation("MacMini");
                });
#pragma warning restore 612, 618
        }
    }
}
